Wiki update
OpenSC/Wiki pull request #15
Opened 2024-04-29 19:27 UTC by xhanulik

Second batch of wiki update (after #14).

2024-04-29 22:17 UTC, frankmorgner requested changes

2024-04-30 15:42 UTC, frankmorgner requested changes
I looked through the pages and made some general suggestions.

If you find the time, you may also look at the CI's comments regarding the spelling.

Thank you!

2024-04-30 18:39 UTC, xhanulik commented on How-to-write-a-good-bug-report.md
> +````text
This was part of https://github.com/OpenSC/Wiki/commit/588feb014779fe277726693f0c7916339f19ce36, I think it intentional to keep the inner backticks.

2024-04-30 18:45 UTC, xhanulik commented on Resources,-Links.md
> +* [PKCS #15](https://www.usenix.org/legacy/publications/library/proceedings/smartcard99/full_papers/nystrom/nystrom_html/index.html): Cryptographic Token Information Format Standard
I think the whitespace should be there as it is written that way also in the linked docs (and the link work fine).

2024-04-30 18:48 UTC, xhanulik commented on Schlumberger-Axalto-Gemalto-e-gate.md
> +As of 2009 the e-gate adapter and both Cryptoflex and Cyberflex are discontinued products.
`cyberflex` and `flex` drivers are already _deactivated_ in `old_card_drivers`, so they are on the way to be removed

2024-04-30 19:07 UTC, xhanulik commented
Thanks for review, I will fix rest of the spelling errors in the third (and last) PR with updates.

2024-05-03 10:52 UTC, merged